export const SET_REPOSITORIES = 'SET_REPOSITORIES';
export const SET_ACTIVE_REPOSITORY = 'SET_ACTIVE_REPOSITORY';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_AFTER = 'SET_AFTER';
export const SET_PAGE = 'SET_PAGE';
export const SAVE_DATA_TO_STORAGE = 'SAVE_DATA_TO_STORAGE';